/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Juan Pablo
 */
public class ViewsBlocDNotas extends javax.swing.JFrame {

    /**
     * Creates new form ViewsBlocDNotas
     */
    public ViewsBlocDNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Archivo = new javax.swing.JTextArea();
        jmb_Archivo = new javax.swing.JMenuBar();
        jm_Menu = new javax.swing.JMenu();
        jmi_Guardar = new javax.swing.JMenuItem();
        jmi_Leer = new javax.swing.JMenuItem();
        jmi_cifrar = new javax.swing.JMenuItem();
        jmi_descifrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 51, 255));

        jta_Archivo.setColumns(20);
        jta_Archivo.setRows(5);
        jScrollPane1.setViewportView(jta_Archivo);

        jm_Menu.setText("File");

        jmi_Guardar.setText("Guardar");
        jm_Menu.add(jmi_Guardar);

        jmi_Leer.setText("Leer");
        jm_Menu.add(jmi_Leer);

        jmi_cifrar.setText("Cifrar Texto");
        jm_Menu.add(jmi_cifrar);

        jmi_descifrar.setText("Descifrar Texto");
        jm_Menu.add(jmi_descifrar);

        jmb_Archivo.add(jm_Menu);

        setJMenuBar(jmb_Archivo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewsBlocDNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewsBlocDNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewsBlocDNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewsBlocDNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewsBlocDNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JMenu jm_Menu;
    public javax.swing.JMenuBar jmb_Archivo;
    public javax.swing.JMenuItem jmi_Guardar;
    public javax.swing.JMenuItem jmi_Leer;
    public javax.swing.JMenuItem jmi_cifrar;
    public javax.swing.JMenuItem jmi_descifrar;
    public javax.swing.JTextArea jta_Archivo;
    // End of variables declaration//GEN-END:variables
}
