/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Juan Pablo
 */
public class ViewsCalculeitor extends javax.swing.JFrame {

    /**
     * Creates new form ViewsCalculeitor
     */
    public ViewsCalculeitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_Div = new javax.swing.JButton();
        jb_Res = new javax.swing.JButton();
        jb_Mult = new javax.swing.JButton();
        jb_Mod = new javax.swing.JButton();
        jb_Sum = new javax.swing.JButton();
        jtf_Numero2 = new javax.swing.JTextField();
        jtf_Numero1 = new javax.swing.JTextField();
        jl_Numero1 = new javax.swing.JLabel();
        jl_Numero2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_Div.setBackground(new java.awt.Color(0, 153, 153));
        jb_Div.setText("División");
        getContentPane().add(jb_Div, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 100, -1));

        jb_Res.setBackground(new java.awt.Color(0, 153, 153));
        jb_Res.setText("Resta");
        getContentPane().add(jb_Res, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jb_Mult.setBackground(new java.awt.Color(0, 153, 153));
        jb_Mult.setText("Multiplicación");
        getContentPane().add(jb_Mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jb_Mod.setBackground(new java.awt.Color(0, 153, 153));
        jb_Mod.setText("Módulo");
        getContentPane().add(jb_Mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jb_Sum.setBackground(new java.awt.Color(0, 153, 153));
        jb_Sum.setText("Suma");
        getContentPane().add(jb_Sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jtf_Numero2.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(jtf_Numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 82, 134, -1));

        jtf_Numero1.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(jtf_Numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 24, 134, -1));

        jl_Numero1.setText("Numero1");
        getContentPane().add(jl_Numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 27, 80, -1));

        jl_Numero2.setText("Numero2");
        getContentPane().add(jl_Numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 85, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("Z:\\Hatsune Miku\\119990.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_Calcular3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Calcular3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_Calcular3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewsCalculeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewsCalculeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewsCalculeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewsCalculeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewsCalculeitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton jb_Div;
    public javax.swing.JButton jb_Mod;
    public javax.swing.JButton jb_Mult;
    public javax.swing.JButton jb_Res;
    public javax.swing.JButton jb_Sum;
    private javax.swing.JLabel jl_Numero1;
    private javax.swing.JLabel jl_Numero2;
    public javax.swing.JTextField jtf_Numero1;
    public javax.swing.JTextField jtf_Numero2;
    // End of variables declaration//GEN-END:variables
}
