package views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Zeo
 */
public class ViewAgenda extends javax.swing.JFrame {

    /**
     * Creates new form ViewAgenda
     */
    public ViewAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_nombre = new javax.swing.JLabel();
        jl_email = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_email = new javax.swing.JTextField();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jb_Nuevo = new javax.swing.JButton();
        jb_Insertar = new javax.swing.JButton();
        jb_Modificacion = new javax.swing.JButton();
        jb_Eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_nombre.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jl_nombre.setForeground(new java.awt.Color(0, 204, 204));
        jl_nombre.setText("Nombre");
        getContentPane().add(jl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 50, -1, -1));

        jl_email.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jl_email.setForeground(new java.awt.Color(0, 204, 204));
        jl_email.setText("Email");
        getContentPane().add(jl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 105, -1, -1));
        getContentPane().add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 50, 180, -1));
        getContentPane().add(jtf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 102, 180, -1));

        jbtn_primero.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jbtn_primero.setForeground(new java.awt.Color(0, 153, 153));
        jbtn_primero.setText("|<");
        getContentPane().add(jbtn_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 153, -1, -1));

        jbtn_anterior.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jbtn_anterior.setForeground(new java.awt.Color(0, 153, 153));
        jbtn_anterior.setText("<<");
        getContentPane().add(jbtn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 153, -1, -1));

        jbtn_siguiente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jbtn_siguiente.setForeground(new java.awt.Color(0, 153, 153));
        jbtn_siguiente.setText(">>");
        getContentPane().add(jbtn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 153, -1, -1));

        jbtn_ultimo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jbtn_ultimo.setForeground(new java.awt.Color(0, 153, 153));
        jbtn_ultimo.setText(">|");
        getContentPane().add(jbtn_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 153, -1, -1));

        jb_Nuevo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jb_Nuevo.setForeground(new java.awt.Color(0, 153, 153));
        jb_Nuevo.setText("Nuevo");
        getContentPane().add(jb_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 204, -1, -1));

        jb_Insertar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jb_Insertar.setForeground(new java.awt.Color(0, 153, 153));
        jb_Insertar.setText("Insertar");
        getContentPane().add(jb_Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 204, -1, -1));

        jb_Modificacion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jb_Modificacion.setForeground(new java.awt.Color(0, 153, 153));
        jb_Modificacion.setText("Modificar");
        getContentPane().add(jb_Modificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 204, -1, -1));

        jb_Eliminar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jb_Eliminar.setForeground(new java.awt.Color(0, 153, 153));
        jb_Eliminar.setText("Eliminar");
        getContentPane().add(jb_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 238, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("Z:\\Hatsune Miku\\48405.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 392, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton jb_Eliminar;
    public javax.swing.JButton jb_Insertar;
    public javax.swing.JButton jb_Modificacion;
    public javax.swing.JButton jb_Nuevo;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_email;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JTextField jtf_email;
    public javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
