/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Juan Pablo
 */
public class ViewsBD extends javax.swing.JFrame {

    /**
     * Creates new form ViewsBD
     */
    public ViewsBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_Nombre = new javax.swing.JTextField();
        jtf_Mail = new javax.swing.JTextField();
        jl_Name = new javax.swing.JLabel();
        jl_Mail = new javax.swing.JLabel();
        jb_Save = new javax.swing.JButton();
        jb_Limpiar = new javax.swing.JButton();
        jb_Primer = new javax.swing.JButton();
        jb_Anterior = new javax.swing.JButton();
        jb_Siguiente = new javax.swing.JButton();
        jb_Ultimo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jmb_Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_open = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_Nombre.setForeground(new java.awt.Color(0, 153, 153));
        jtf_Nombre.setText("Tu bello nombre");
        getContentPane().add(jtf_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 44, 223, -1));

        jtf_Mail.setForeground(new java.awt.Color(0, 153, 153));
        jtf_Mail.setText("Example@gmail.com");
        getContentPane().add(jtf_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 120, 223, -1));

        jl_Name.setForeground(new java.awt.Color(0, 153, 153));
        jl_Name.setText("Nombre");
        getContentPane().add(jl_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, 79, -1));

        jl_Mail.setForeground(new java.awt.Color(0, 153, 153));
        jl_Mail.setText("E-Mail");
        getContentPane().add(jl_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 87, -1));

        jb_Save.setForeground(new java.awt.Color(0, 153, 153));
        jb_Save.setText("Guardar");
        getContentPane().add(jb_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 245, -1, -1));

        jb_Limpiar.setForeground(new java.awt.Color(0, 153, 153));
        jb_Limpiar.setText("Limpiar");
        getContentPane().add(jb_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 245, -1, -1));

        jb_Primer.setForeground(new java.awt.Color(0, 153, 153));
        jb_Primer.setText("Primer");
        getContentPane().add(jb_Primer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, -1, -1));

        jb_Anterior.setForeground(new java.awt.Color(0, 153, 153));
        jb_Anterior.setText("Anterior");
        getContentPane().add(jb_Anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 169, -1, -1));

        jb_Siguiente.setForeground(new java.awt.Color(0, 153, 153));
        jb_Siguiente.setText("Siguiente");
        getContentPane().add(jb_Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 169, -1, -1));

        jb_Ultimo.setForeground(new java.awt.Color(0, 153, 153));
        jb_Ultimo.setText("Ultimo");
        getContentPane().add(jb_Ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 169, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/612533.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 390, 280));

        jmb_Menu.setBackground(new java.awt.Color(0, 102, 102));
        jmb_Menu.setForeground(new java.awt.Color(0, 153, 153));

        jMenu1.setText("File");

        jmi_open.setText("Abrir");
        jMenu1.add(jmi_open);

        jmb_Menu.add(jMenu1);

        setJMenuBar(jmb_Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewsBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewsBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewsBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewsBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewsBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JButton jb_Anterior;
    public javax.swing.JButton jb_Limpiar;
    public javax.swing.JButton jb_Primer;
    public javax.swing.JButton jb_Save;
    public javax.swing.JButton jb_Siguiente;
    public javax.swing.JButton jb_Ultimo;
    private javax.swing.JLabel jl_Mail;
    private javax.swing.JLabel jl_Name;
    public javax.swing.JMenuBar jmb_Menu;
    public javax.swing.JMenuItem jmi_open;
    public javax.swing.JTextField jtf_Mail;
    public javax.swing.JTextField jtf_Nombre;
    // End of variables declaration//GEN-END:variables
}
