package views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Zeo
 */
public class ViewAgenda extends javax.swing.JFrame {

    /**
     * Creates new form ViewAgenda
     */
    public ViewAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_nombre = new javax.swing.JLabel();
        jl_email = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_email = new javax.swing.JTextField();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jb_Nuevo = new javax.swing.JButton();
        jb_Insertar = new javax.swing.JButton();
        jb_Modificacion = new javax.swing.JButton();
        jb_Eliminar = new javax.swing.JButton();
        jl_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_nombre.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jl_nombre.setForeground(new java.awt.Color(0, 204, 204));
        jl_nombre.setText("Nombre");
        jl_nombre.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(0, 102, 204)));
        getContentPane().add(jl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 50, 50, -1));

        jl_email.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jl_email.setForeground(new java.awt.Color(0, 204, 204));
        jl_email.setText("Email");
        jl_email.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(0, 102, 204)));
        getContentPane().add(jl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 105, 50, -1));

        jtf_nombre.setBackground(new java.awt.Color(0, 102, 204));
        jtf_nombre.setForeground(new java.awt.Color(0, 204, 204));
        jtf_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153)));
        getContentPane().add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 50, 180, -1));

        jtf_email.setBackground(new java.awt.Color(0, 102, 204));
        jtf_email.setForeground(new java.awt.Color(0, 204, 204));
        jtf_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153)));
        getContentPane().add(jtf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 102, 180, -1));

        jbtn_primero.setBackground(new java.awt.Color(204, 204, 255));
        jbtn_primero.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jbtn_primero.setForeground(new java.awt.Color(0, 153, 153));
        jbtn_primero.setText("|<");
        jbtn_primero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 51, 255)));
        getContentPane().add(jbtn_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, -1));

        jbtn_anterior.setBackground(new java.awt.Color(204, 204, 255));
        jbtn_anterior.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jbtn_anterior.setForeground(new java.awt.Color(0, 153, 153));
        jbtn_anterior.setText("<<");
        jbtn_anterior.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 51, 255)));
        getContentPane().add(jbtn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 60, -1));

        jbtn_siguiente.setBackground(new java.awt.Color(204, 204, 255));
        jbtn_siguiente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jbtn_siguiente.setForeground(new java.awt.Color(0, 153, 153));
        jbtn_siguiente.setText(">>");
        jbtn_siguiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 51, 255)));
        getContentPane().add(jbtn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 60, -1));

        jbtn_ultimo.setBackground(new java.awt.Color(204, 204, 255));
        jbtn_ultimo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jbtn_ultimo.setForeground(new java.awt.Color(0, 153, 153));
        jbtn_ultimo.setText(">|");
        jbtn_ultimo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 51, 255)));
        getContentPane().add(jbtn_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 50, -1));

        jb_Nuevo.setBackground(new java.awt.Color(204, 204, 255));
        jb_Nuevo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jb_Nuevo.setForeground(new java.awt.Color(0, 153, 153));
        jb_Nuevo.setText("Nuevo");
        jb_Nuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 51, 255)));
        getContentPane().add(jb_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 70, -1));

        jb_Insertar.setBackground(new java.awt.Color(204, 204, 255));
        jb_Insertar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jb_Insertar.setForeground(new java.awt.Color(0, 153, 153));
        jb_Insertar.setText("Insertar");
        jb_Insertar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 51, 255)));
        getContentPane().add(jb_Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 80, -1));

        jb_Modificacion.setBackground(new java.awt.Color(204, 204, 255));
        jb_Modificacion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jb_Modificacion.setForeground(new java.awt.Color(0, 153, 153));
        jb_Modificacion.setText("Modificar");
        jb_Modificacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 51, 255)));
        getContentPane().add(jb_Modificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 90, -1));

        jb_Eliminar.setBackground(new java.awt.Color(204, 204, 255));
        jb_Eliminar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jb_Eliminar.setForeground(new java.awt.Color(0, 153, 153));
        jb_Eliminar.setText("Eliminar");
        jb_Eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 51, 255)));
        getContentPane().add(jb_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 80, -1));

        jl_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/48405.jpg"))); // NOI18N
        getContentPane().add(jl_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 392, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_Eliminar;
    public javax.swing.JButton jb_Insertar;
    public javax.swing.JButton jb_Modificacion;
    public javax.swing.JButton jb_Nuevo;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    private javax.swing.JLabel jl_Wallpaper;
    public javax.swing.JLabel jl_email;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JTextField jtf_email;
    public javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
