/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Juan Pablo
 */
public class ViewsIMC extends javax.swing.JFrame {

    /**
     * Creates new form IMC
     */
    public ViewsIMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_Peso = new javax.swing.JTextField();
        jtf_Altura = new javax.swing.JTextField();
        jb_Calcular = new javax.swing.JButton();
        jl_IMC = new javax.swing.JLabel();
        jl_Peso = new javax.swing.JLabel();
        jl_Altura = new javax.swing.JLabel();
        jtf_IMC = new javax.swing.JTextField();
        jl_Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jtf_Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 68, 106, -1));
        getContentPane().add(jtf_Altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 141, 106, -1));

        jb_Calcular.setText("Calcula");
        getContentPane().add(jb_Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 226, 106, -1));

        jl_IMC.setForeground(new java.awt.Color(0, 204, 204));
        jl_IMC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_IMC.setText("Calcula tu IMC");
        getContentPane().add(jl_IMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 11, 106, -1));

        jl_Peso.setForeground(new java.awt.Color(0, 204, 204));
        jl_Peso.setText("Peso");
        getContentPane().add(jl_Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 68, -1));

        jl_Altura.setForeground(new java.awt.Color(0, 204, 204));
        jl_Altura.setText("Altura");
        getContentPane().add(jl_Altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 144, 68, -1));
        getContentPane().add(jtf_IMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 260, 200, -1));

        jl_Imagen.setIcon(new javax.swing.ImageIcon("Z:\\Hatsune Miku\\119953.jpg")); // NOI18N
        getContentPane().add(jl_Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewsIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewsIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewsIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewsIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewsIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_Calcular;
    private javax.swing.JLabel jl_Altura;
    public javax.swing.JLabel jl_IMC;
    private javax.swing.JLabel jl_Imagen;
    private javax.swing.JLabel jl_Peso;
    public javax.swing.JTextField jtf_Altura;
    public javax.swing.JTextField jtf_IMC;
    public javax.swing.JTextField jtf_Peso;
    // End of variables declaration//GEN-END:variables
}
